#ifndef _CONSTANTS_HPP
#define _CONSTANTS_HPP


#define DEBUG
#define BLUETOOTH

#define LED_PIN 13

#define BLUEFRUIT_SPI_CS 8
#define BLUEFRUIT_SPI_IRQ 7
#define BLUEFRUIT_SPI_RST 4

#define LL_IR_PIN A0
#define L_IR_PIN A1
#define R_IR_PIN A2
#define RR_IR_PIN A3

#define LEFT_FRONT_MOTOR_PORT 3
#define LEFT_BACK_MOTOR_PORT 4
#define RIGHT_FRONT_MOTOR_PORT 2
#define RIGHT_BACK_MOTOR_PORT 1

#define IR_THRESHOLD 500
#define LUX_THRESHOLD 3000


#endif  // #ifndef _CONSTANTS_HPP
